server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

    properties:
      use.latest.version: false
      auto.register.schemas: false
      basic.auth:
        credentials.source: USER_INFO
        user.info: user:password
      schema:
        registry:
          url: http://localhost:8081

      spring:
        deserializer:
          value:
            delegate:
              class: io.confluent.kafka.serializers.KafkaAvroDeserializer

      specific:
        avro:
          reader: true

    listener:
      missing-topics-fatal: false
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 2

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      group-id: testing-group
      auto-offset-reset: earliest
      max-poll-records: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

kafka:
  replay-enabled: true

  topics:
    main-topic: test-topic
    forwarding-topic: forwarding-topic

  producer:
    auto-producer-enabled: false

retry:
  consumer:
    backoff-ms: 5000
    max-attempts: 5